### PR TITLE
fix: resolve the gst profile running issue from profile-launcher

### PR DESCRIPTION
**Pull request by jim-wang-intel**
FIXES: #226

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## Issue this PR will close

close: #**226**

## Test Instructions if applicable

- git clone this PR
- make build-profile-launcher
- run camera-simulator: `$ ./camera-simulator/camera-simulator.sh`
- run gst profile: 
```console
$  PIPELINE_PROFILE="gst" RENDER_MODE=0 sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 
```

observe that now the pipeline is running ok and outputs fps in `pipeline0.log` file under ./results/ folder.
- You can also test the stream-density for gst profile now too: 
```console
$ cd ./benchmark-scripts
$ PIPELINE_PROFILE="gst" RENDER_MODE=0 sudo -E ./benchmark.sh --stream_density 14.95  --logdir gst/data --duration 120 --init_duration 40 --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
```

### CODE REVIEW

**Review by brian-intel — APPROVED** [review]

**Review by vli11 — COMMENTED** [review]
the test instructions are working, but when I tried to have RENDER_MODE=1, the streaming has never come up

**Comment by jim-wang-intel** [comment]
> the test instructions are working, but when I tried to have RENDER_MODE=1, the streaming has never come up

what is the streaming, could you give more details?

**Comment by vli11** [comment]
> > the test instructions are working, but when I tried to have RENDER_MODE=1, the streaming has never come up
> 
> what is the streaming, could you give more details?

video playing of the result.

**Comment by jim-wang-intel** [comment]
> > > the test instructions are working, but when I tried to have RENDER_MODE=1, the streaming has never come up
> > 
> > 
> > what is the streaming, could you give more details?
> 
> video playing of the result.

there is no video play for this profile.

**Comment by vli11** [comment]
> > > > the test instructions are working, but when I tried to have RENDER_MODE=1, the streaming has never come up
> > > 
> > > 
> > > what is the streaming, could you give more details?
> > 
> > 
> > video playing of the result.
> 
> there is no video play for this profile. that is the re-streaming post process that user has to put manually. currently we don't have such logic in this gst profile i believe

i see, thanks for explanation!

**Review by vli11 — APPROVED** [review]

**Comment by jim-wang-intel** [comment]
rebase to merge changes from main branch

**Pull request merged**
