### PR TITLE
Expand profile-launcher configs to support the generic docker-run script

### PR DESCRIPTION
**Pull request by jim-wang-intel**
Add more configuration into profile-launcher (pl) so that it can support the generic docker-run script that Brian is working on.

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## Issue this PR will close

close: #**issue_number**

## Test Instructions if applicable

You can run smoke test and everything should pass:
```console
make run-smoke-tests
```

```text
results of smoke tests recorded in the file smoke_tests_output.log
=== test rtsp://127.0.0.1:8554/camera_0 profile smoke test status code PASSED
=== classification rtsp://127.0.0.1:8554/camera_0 profile smoke test status code PASSED
=== classification rtsp://127.0.0.1:8554/camera_0 profile smoke test pipeline log PASSED
=== grpc_go rtsp://127.0.0.1:8554/camera_0 profile smoke test status code PASSED
=== grpc_go rtsp://127.0.0.1:8554/camera_0 profile smoke test pipeline log PASSED
=== grpc_python rtsp://127.0.0.1:8554/camera_0 profile smoke test status code PASSED
=== grpc_python rtsp://127.0.0.1:8554/camera_0 profile smoke test pipeline log PASSED
=== gst rtsp://127.0.0.1:8554/camera_0 profile smoke test status code PASSED
=== gst rtsp://127.0.0.1:8554/camera_0 profile smoke test pipeline log PASSED
=== instance_segmentation rtsp://127.0.0.1:8554/camera_0 profile smoke test status code PASSED
=== instance_segmentation rtsp://127.0.0.1:8554/camera_0 profile smoke test pipeline log PASSED
=== object_detection rtsp://127.0.0.1:8554/camera_1 profile smoke test status code PASSED
=== object_detection rtsp://127.0.0.1:8554/camera_1 profile smoke test pipeline log PASSED
```

### CODE REVIEW

**Comment by jim-wang-intel** [comment]
rebased to resolve the conflicts from main

**Review by vli11 — APPROVED** [review]
tested in my system, looks good to me

**Review by brian-intel — APPROVED** [review]
LGTM

**Review by antoniomtz — APPROVED** [review]
LGTM. Test passed

**Pull request merged**
