### PR TITLE
feat: enhance getting realsense camera serial number into a script and makefile target

### PR DESCRIPTION
**Pull request by jim-wang-intel**
## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [x] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## Issue this PR will close

close: #**306**

## Test Instructions if applicable

- git clone this PR
- plug in your realsense camera into system
- run build: `make build-dlstreamer-realsense`
- run get serial number makefile target: `make get-realsense-serial-num`

### CODE REVIEW

**Review by vli11 — COMMENTED** [review]
does reading realsense serialnumber need to relate to dlstream? this is just a consideration that we may remove dlstreamer in the future.

**Comment by jim-wang-intel** [comment]
> does reading realsense serialnumber need to relate to dlstream? this is just a consideration that we may remove dlstreamer in the future.

that is a good question, using the dlstreamer docker image is the only way i know available now in this repo.  please suggest another way if you can find. thanks.

**Review by vli11 — APPROVED** [review]
look it up online for a while, the result only printed out the asic serial number; I think this is the only way now

**Comment by jim-wang-intel** [comment]
rebased to merge updates from main branch, and resolved the conflicts

**Review by ejlee3 — APPROVED** [review]
LGTM

**Pull request merged**
