### PR TITLE
fix: Update xpu manager release

### PR DESCRIPTION
**Pull request by brian-intel**
## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [x] All commented code has been removed
- [x] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

Updating XPU manager as a result of the previous version being removed from github

## Issue this PR will close

close: #394 

## Test Instructions if applicable

1. cd benchmark-scripts
2. make build-xpu or make build-all
3. See failure

### CODE REVIEW

**Review by jim-wang-intel — COMMENTED** [review]
why this is a breaking change?

**Review by antoniomtz — APPROVED** [review]
LGTM

**Review by vli11 — APPROVED** [review]
lgtm

**Comment by brian-intel** [comment]
> why this is a breaking change?

Technically it's a fixing change since the current version is broken but I see your point. I'll remove that tag since it's not really the intent.

**Review by jim-wang-intel — APPROVED** [review]

**Pull request merged**
